### ISSUE TITLE
remove v0.2.0 artifacts

### ISSUE THREAD

**Issue by MementoRC** [conda-forge/libsecp256k1-feedstock#11]
### Comment:

The v0.2.0 mistakenly shipped a statically linked `libsecp256k1` library. It uses 1M by itself @conda-forge/core

**Comment by MementoRC** [comment]
Wrong action: ignore

**Comment by ocefpaf** [comment]
If you ever need to mark pkgs as broken see https://github.com/conda-forge/admin-requests?tab=readme-ov-file#mark-packages-as-broken-on-conda-forge

**Comment by MementoRC** [comment]
Right, I was reading the Maintainer KB and mixed-up the broken and archive paragraph. I pushed: https://github.com/conda-forge/admin-requests/pull/960
Let me know if this is correct, if you get the chance
Thanks
